spring:
  liquibase:
    enabled: false
    change-log: classpath:db/master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/card_processing_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

secret:
  key: my-super-secretKey_my-super-secretKey_my-super-secretKey
  refresh-token:
    expiry: 21600000
cbu:
  base-url: https://cbu.uz
  end-point: /ru/arkhiv-kursov-valyut/json/all/