spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.yaml

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:card_processing_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

secret:
  key: my-super-secretKey_my-super-secretKey_my-super-secretKey
  refresh-token:
    expiry: 900000
cbu:
  base-url: https://cbu.uz
  end-point: /ru/arkhiv-kursov-valyut/json/all/